# Generated by Django 3.2.25 on 2026-03-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('source', models.CharField(choices=[('olx', 'OLX'), ('telegram', 'Telegram'), ('manual', 'Вручну')], max_length=20, verbose_name='Джерело')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('verified', 'Перевірена'), ('rejected', 'Відхилена')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Заявка на перевірку',
                'verbose_name_plural': 'Заявки на перевірку',
                'ordering': ['-created_at'],
            },
        ),
    ]
